// <auto-generated />
namespace Shop.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JsonProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JsonProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011703286_JsonProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
