// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Shop;
using Shop.Models;

namespace Shop
{
    public static partial class CategoriesExtensions
    {
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Category Get(this ICategories operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICategories)s).GetAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Category> GetAsync(this ICategories operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Shop.Models.Category> result = await operations.GetWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        public static IList<Category> GetAll(this ICategories operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICategories)s).GetAllAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Category>> GetAllAsync(this ICategories operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Shop.Models.Category>> result = await operations.GetAllWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        public static IList<Category> GetAllTopCategories(this ICategories operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICategories)s).GetAllTopCategoriesAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Category>> GetAllTopCategoriesAsync(this ICategories operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Shop.Models.Category>> result = await operations.GetAllTopCategoriesWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static IList<Product> GetProductsFromCategory(this ICategories operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICategories)s).GetProductsFromCategoryAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Product>> GetProductsFromCategoryAsync(this ICategories operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Shop.Models.Product>> result = await operations.GetProductsFromCategoryWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static IList<Category> GetTopCategories(this ICategories operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICategories)s).GetTopCategoriesAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.ICategories.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Category>> GetTopCategoriesAsync(this ICategories operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Shop.Models.Category>> result = await operations.GetTopCategoriesWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
