// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Shop;
using Shop.Models;

namespace Shop
{
    public static partial class OrdersExtensions
    {
        /// <param name='operations'>
        /// Reference to the Shop.IOrders.
        /// </param>
        /// <param name='newOrder'>
        /// Required.
        /// </param>
        public static object Post(this IOrders operations, OrderViewModel newOrder)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOrders)s).PostAsync(newOrder);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Shop.IOrders.
        /// </param>
        /// <param name='newOrder'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostAsync(this IOrders operations, OrderViewModel newOrder, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostWithOperationResponseAsync(newOrder, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
