// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Shop.Models
{
    public partial class Category
    {
        private int? _baseCategoryId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? BaseCategoryId
        {
            get { return this._baseCategoryId; }
            set { this._baseCategoryId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private IList<string> _properties;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> Properties
        {
            get { return this._properties; }
            set { this._properties = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category()
        {
            this.Properties = new LazyList<string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken baseCategoryIdValue = inputObject["BaseCategoryId"];
                if (baseCategoryIdValue != null && baseCategoryIdValue.Type != JTokenType.Null)
                {
                    this.BaseCategoryId = ((int)baseCategoryIdValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken propertiesSequence = ((JToken)inputObject["Properties"]);
                if (propertiesSequence != null && propertiesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken propertiesValue in ((JArray)propertiesSequence))
                    {
                        this.Properties.Add(((string)propertiesValue));
                    }
                }
            }
        }
    }
}
