// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Shop.Models;

namespace Shop.Models
{
    public static partial class ImageCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Image> DeserializeJson(JToken inputObject)
        {
            IList<Image> deserializedObject = new List<Image>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Image image = new Image();
                image.DeserializeJson(iListValue);
                deserializedObject.Add(image);
            }
            return deserializedObject;
        }
    }
}
