// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Shop.Models
{
    public partial class ImageViewModel
    {
        private int? _productId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ProductId
        {
            get { return this._productId; }
            set { this._productId = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ImageViewModel class.
        /// </summary>
        public ImageViewModel()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ImageViewModel
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ProductId != null)
            {
                outputObject["ProductId"] = this.ProductId.Value;
            }
            if (this.Url != null)
            {
                outputObject["Url"] = this.Url;
            }
            return outputObject;
        }
    }
}
