// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Shop.Models
{
    public partial class Review
    {
        private string _authorId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AuthorId
        {
            get { return this._authorId; }
            set { this._authorId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private int? _productId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ProductId
        {
            get { return this._productId; }
            set { this._productId = value; }
        }
        
        private int? _rate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Rate
        {
            get { return this._rate; }
            set { this._rate = value; }
        }
        
        private string _reviewText;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ReviewText
        {
            get { return this._reviewText; }
            set { this._reviewText = value; }
        }
        
        private DateTimeOffset? _reviewTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ReviewTime
        {
            get { return this._reviewTime; }
            set { this._reviewTime = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Review class.
        /// </summary>
        public Review()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken authorIdValue = inputObject["AuthorId"];
                if (authorIdValue != null && authorIdValue.Type != JTokenType.Null)
                {
                    this.AuthorId = ((string)authorIdValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken productIdValue = inputObject["ProductId"];
                if (productIdValue != null && productIdValue.Type != JTokenType.Null)
                {
                    this.ProductId = ((int)productIdValue);
                }
                JToken rateValue = inputObject["Rate"];
                if (rateValue != null && rateValue.Type != JTokenType.Null)
                {
                    this.Rate = ((int)rateValue);
                }
                JToken reviewTextValue = inputObject["ReviewText"];
                if (reviewTextValue != null && reviewTextValue.Type != JTokenType.Null)
                {
                    this.ReviewText = ((string)reviewTextValue);
                }
                JToken reviewTimeValue = inputObject["ReviewTime"];
                if (reviewTimeValue != null && reviewTimeValue.Type != JTokenType.Null)
                {
                    this.ReviewTime = ((DateTimeOffset)reviewTimeValue);
                }
            }
        }
    }
}
